name: Lighthouse CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Storybook
        run: npm run build-storybook
        
      - name: Run Lighthouse CI
        run: npm run lighthouse
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        
      - name: Upload Lighthouse Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 30
          
      - name: Comment PR with Lighthouse Results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read Lighthouse CI results
            const resultsPath = '.lighthouseci';
            if (fs.existsSync(resultsPath)) {
              const comment = `## 📊 Lighthouse CI Results
              
              Lighthouse audits have been completed! 
              
              📥 [Download detailed reports](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
              
              ⚡ Check the artifacts section for full Lighthouse reports.`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            }
