name: publish-reports

on:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, linux, X64, linux_desktop]
    strategy:
      matrix:
        environment_name: [github-pages]
    environment:
      name: ${{ matrix.environment_name }}
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Download storybook artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: storybook-static
          path: storybook
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release reports artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: release-reports
          path: reports
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true

      - name: Install Python 3.12 for uv
        run: uv python install 3.12

      - name: Checkout repository for scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/prepare-report-site.py
          sparse-checkout-cone-mode: false
          path: repo

      - name: Prepare report site
        run: |
          set -euo pipefail
          mkdir -p site
          if [ -f storybook/storybook-static.tar.gz ]; then
            tar -xzf storybook/storybook-static.tar.gz -C site
          else
            echo "storybook-static.tar.gz not found" >&2
            exit 1
          fi
          mkdir -p site/coverage site/lighthouse
          cp -a reports/coverage/lcov-report/. site/coverage/
          cp -a .lighthouseci/. site/lighthouse/
          ls -al
          uv run python repo/scripts/prepare-report-site.py

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
